AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Assessment Serverless Function

Resources:
  NotificationAndTemplate:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: lambdaImage:rapid-x86_64
      CodeUri: C:\work\java\eclipse-workspace2\AWS-lambda-assessment
      Architectures:
        - x86_64
      Timeout: 120
      MemorySize: 4096
      Events:
        CreateNotification:
          Type: Api 
          Properties:
            Path: /v1/createNotification
            Method: post
        FindAllNotifications:
          Type: Api
          Properties:
            Path: /v1/all/notifications
            Method: get
        FindNotificationById:
          Type: Api
          Properties:
            Path: /v1/findByNotificationId/{id}
            Method: get
        CreateTemplate:
          Type: Api 
          Properties:
            Path: /v1/createTemplate
            Method: post
        FindAllTemplates:
          Type: Api
          Properties:
            Path: /v1/all/templates
            Method: get
        FindTemplateById:
          Type: Api
          Properties:
            Path: /v1/findByTemplateId/{id}
            Method: get
        UpdateTemplate:
          Type: Api
          Properties:
            Path: /v1/updateTemplate
            Method: patch
        ShutdownHook:
          Type: Api
          Properties:
            Path: /v1/shutdown
            Method: get
    Metadata:  # <--- Metadata section to help SAM manage container images
      DockerTag: rapid-x86_64
      DockerContext: .  # <--- Points to the directory with your Dockerfile
      Dockerfile: Dockerfile  # <--- Name of the Docker			
