Globals:
    Function:
        Timeout: 120
        MemorySize: 4096
        Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
          Variables:
            DB_URL: jdbc:postgresql://postgres/postgres
            DB_USER: postgres
            DB_PASSWORD: sa
            SAM_CLI_CONTAINER_CONNECTION_TIMEOUT: 120

Parameters:
  DockerTag:
    Type: String
    Default: rapid-x86_64
  HandlersInvokeParam:
    Type: String
    Default: request.handlers.NotificationAndTemplateHandler::handleRequest

Resources:
  NotificationAndTemplate:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: lambdaImage:rapid-x86_64
      CodeUri: C:\work\java\eclipse-workspace2\AWS-lambda-assessment
      Handler: request.handlers.NotificationAndTemplateHandler::handleRequest
      Architectures:
        - x86_64
      Runtime: java21
      Timeout: 120
      MemorySize: 4096
      Events:
        CreateNotification:
          Type: Api 
          Properties:
            Path: /v1/createNotification
            Method: post
        FindAllNotifications:
          Type: Api
          Properties:
            Path: /v1/all/notifications
            Method: get
        FindNotificationById:
          Type: Api
          Properties:
            Path: /v1/findByNotificationId/{id}
            Method: get
        CreateTemplate:
          Type: Api 
          Properties:
            Path: /v1/createTemplate
            Method: post
        FindAllTemplates:
          Type: Api
          Properties:
            Path: /v1/all/templates
            Method: get
        FindTemplateById:
          Type: Api
          Properties:
            Path: /v1/findByTemplateId/{id}
            Method: get
        UpdateTemplate:
          Type: Api
          Properties:
            Path: /v1/updateTemplate
            Method: patch
        ShutdownHook:
          Type: Api
          Properties:
            Path: /v1/shutdown
            Method: get
    Metadata:  # <--- Metadata section to help SAM manage container images
      DockerTag: rapid-x86_64
      DockerContext: .  # <--- Points to the directory with your Dockerfile
      Dockerfile: Dockerfile  # <--- Name of the Docker			
