AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Assessment Serverless Function

Resources:
  RequestLambdaFunctionAuthorizer:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: LambdaRequestAuthorizer
        Authorizers:
          LambdaRequestAuthorizer:
            FunctionArn: !GetAtt AuthFunction.Arn
            FunctionInvokeRole: arn:aws:iam::153822065620:role/AllowLambdaFunctionRole
            Identity:
              Headers:
                - Authorization
            AuthorizerPayloadFormatVersion: 2.0
            EnableSimpleResponses: true
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: C:\work\java\eclipse-workspace2\AWS-lambda-assessment
      Handler: request.handlers.AuthorizationHandler::handleRequest
      Architectures:
        - x86_64
      Runtime: java21
      Timeout: 120
      MemorySize: 4096
      Events:
        CheckAuthorization:
          Type: HttpApi
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Auth:
              Authorizer: NONE # This overrides the default authorizer, making it public          
            Path: /v1/test/authorization
            Method: get
  NotificationAndTemplate:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: lambdaImage:rapid-x86_64
      CodeUri: C:\work\java\eclipse-workspace2\AWS-lambda-assessment
      Architectures:
        - x86_64
      Timeout: 120
      MemorySize: 4096
      Events:
        CreateNotification:
          Type: HttpApi 
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/createNotification
            Method: post
        FindAllNotifications:
          Type: HttpApi
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/all/notifications
            Method: get
        FindNotificationById:
          Type: HttpApi
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/findByNotificationId/{id}
            Method: get
        CreateTemplate:
          Type: HttpApi 
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/createTemplate
            Method: post
        FindAllTemplates:
          Type: HttpApi
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/all/templates
            Method: get
        FindTemplateById:
          Type: HttpApi
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/findByTemplateId/{id}
            Method: get
        UpdateTemplate:
          Type: HttpApi
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/updateTemplate
            Method: patch
        ShutdownHook:
          Type: HttpApi
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/shutdown
            Method: get
    Metadata:  # <--- Metadata section to help SAM manage container images
      DockerTag: rapid-x86_64
      DockerContext: .  # <--- Points to the directory with your Dockerfile
      Dockerfile: Dockerfile  # <--- Name of the Docker			
