AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Resources:
  RequestLambdaFunctionAuthorizer:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        DefaultAuthorizer: LambdaAuthorizer
        Authorizers: 
          LambdaAuthorizer:
            FunctionArn: !GetAtt AuthFunction.Arn
            FunctionInvokeRole: arn:aws:iam::153822065620:role/AllowLambdaFunctionRole
            AuthorizerPayloadFormatVersion: "2.0"
            EnableFunctionDefaultPermissions: true
            EnableSimpleResponses: true
      CorsConfiguration:
        AllowOrigins:
          - '*' # Or '*' for all origins
        AllowHeaders:
          - 'Content-Type'
          - 'Origin'
          - 'Accept'
          - 'X-Amz-Date'
          - 'Authorization'
          - 'X-Api-Key'
          - 'X-Amz-Security-Token'
          - 'Access-Control-Request-Headers'
          - 'Access-Control-Request-Method'
        AllowMethods:
          - 'GET'
          - 'POST'
          - 'OPTIONS'
          - 'PUT'
          - 'DELETE'
          - 'PATCH'
        ExposeHeaders:
          - 'Content-Type'
          - 'Content-Range'
          - 'Access-Control-Allow-Origin'
          - 'Access-Control-Allow-Methods'
          - 'Access-Control-Allow-Headers'
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: notificationandtemplate:rapid-x86_64
      CodeUri: C:\work\java\eclipse-workspace2\AWS-lambda-assessment
      Architectures:
        - x86_64
      Timeout: 120
      MemorySize: 4096
      Events:
        CheckAuthorization:
          Type: HttpApi
          Properties:
            Path: /v1/test/authorization
            Method: post
  NotificationAndTemplate:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: notificationandtemplate:rapid-x86_64
      CodeUri: C:\work\java\eclipse-workspace2\AWS-lambda-assessment
      Architectures:
        - x86_64
      Timeout: 120
      MemorySize: 4096
      Events:
        CreateNotification:
          Type: HttpApi 
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/createNotification
            Method: post
        FindAllNotifications:
          Type: HttpApi
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/all/notifications
            Method: get
        FindNotificationById:
          Type: HttpApi
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/findByNotificationId/{id}
            Method: get
        CreateTemplate:
          Type: HttpApi 
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/createTemplate
            Method: post
        FindAllTemplates:
          Type: HttpApi
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/all/templates
            Method: get
        FindTemplateById:
          Type: HttpApi
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/findByTemplateId/{id}
            Method: get
        UpdateTemplate:
          Type: HttpApi
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/updateTemplate
            Method: patch
        ShutdownHook:
          Type: HttpApi
          Properties:
            ApiId: !Ref RequestLambdaFunctionAuthorizer
            Path: /v1/shutdown
            Method: get
    Metadata:  # <--- Metadata section to help SAM manage container images
      DockerTag: rapid-x86_64
      DockerContext: .  # <--- Points to the directory with your Dockerfile
      Dockerfile: Dockerfile  # <--- Name of the Docker			
